general:
  input-loom: <PATH>/<FILE>.loom
  output-folder: <PATH>
  samples: 3


algorithms:
  runs: 10
  doublet_rates: [0.08, 0.3]


COMPASS:
  run: False
  exe: <PATH>/COMPASS/COMPASS
  chain_length: 50000

BnpC:
  run: True
  exe: <PATH>/BnpC/run_BnpC.py
  chain_length: 10000

SCG:
  run: False
  wrapper_exe: ../sandbox/SCG_wrapper.py
  exe: <PATH>/scg/scg-0.3.1/scg
  chain_length: 100000

