analysis:
  specific:
    input-dir: <INPUT_DIR>
    output-dir: /cluster/work/bewi/ngs/projects/demoTape/mixed_analysis
    samples: 3
  general:
    gene_annotation: <RESOURCES_DIR>/gencode.v19.annotation.cytoBand.tsv
    panel_annotation: <RESOURCES_DIR>/3848_annotated.bed
    dbsnp: <RESOURCES_DIR>/hg19/ado_db_files/trim_dbsnp153_0.01.txt

  algorithms:
    runs: 10
    doublet_rates: [0.08, 0.25]

    COMPASS:
      run: True
      exe: <COMPASS_DIR>/COMPASS
      chains: 4
      chain_length: 50000
      CNV: 0

    BnpC:
      run: False
      exe: <BNPC_DIR>/run_BnpC.py
      chains: 4
      chain_length: 500
      runtime: 180

    SCG:
      run: False
      wrapper_exe: MINCEDTAPESTRI_DIR>/sandbox/SCG_wrapper.py
      chain_length: 50000

output:
  prefix: <PREFIX>

tapestri:
  output-folder: <OUTPUT_DIR>